name: CI

on:
  push:
    branches: [main]
    paths:
      - "**"
  pull_request:
    branches: [main]
    paths:
      - "**"

jobs:
  test:
    name: Run app tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2

      # Node
      - uses: actions/setup-node@v1
        with:
          node-version: "16"

      - name: Create .env file
        run: |
          touch .env
          echo NODE_ENV=dev >> .env
          echo PORT=8080 >> .env
          echo API_KEY=TESTAPIKEY >> .env
          echo ENCRYPTION_SECRET=TESTSECRET >> .env
          echo JWT_SECRET=TESTJWTSECRET >> .env
          echo MONGO_CLUSTER=${{ secrets.MONGO_CLUSTER }} >> .env
          echo MONGO_USER=${{ secrets.MONGO_USER }} >> .env
          echo MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }} >> .env
          echo MONGO_DBNAME=${{ secrets.MONGO_DBNAME }} >> .env
          echo MONGO_READONLY_USER=${{ secrets.MONGO_READONLY_USER }} >> .env
          echo MONGO_READONLY_PASSWORD=${{ secrets.MONGO_READONLY_PASSWORD }} >> .env
          cat .env

      - name: Node installation
        run: npm install

      - name: Run Tests
        run: npm run test
